#USUARIO SYS
#spring.datasource.username=sys as sysdba
#spring.datasource.password=oracle12c

server:
  servlet:
    context-path: /srem
  port: 8087

# Spring Boot configuration
spring:
  profiles:
    active: development

  # Security configuration
  security:
    user:
      name: user
      password: user

  # Database
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: USR_SREM
    password: USR_SREM
    #username: sys as sysdba    #USUARIO SYS
    #password: oracle12c
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update #update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    generate-ddl: false
  hikari:
    connection-timeout: 20000
    idle-timeout: 600000
    max-lifetime: 1800000


# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: info
    org.springframework: info
    org.hibernate: info

springdoc:
  api-docs:
    path: /api-docs

api:
  version: 1.0-SNAPSHOT
  server:
    url: https://www.srem.com
  description: Music events recommendation system


