--CREACION DE TABLAS
CREATE TABLE USR_SREM.PERSONAS(
    id NUMBER(15),
    name VARCHAR2(100),
    apellidos VARCHAR2(1000),
    PRIMARY KEY (id)
);

--CREACION DE SECUENCIAS
CREATE SEQUENCE  "USR_SREM"."PERSONAS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

select * from personas;
select personas_SEQ.NEXTVAL from dual;

drop table USR_SREM.PERSONAS;
drop sequence USR_SREM.PERSONAS_SEQ;


-----------------------------------------------
--CREACION DE TABLAS
CREATE TABLE USR_SREM.SREMUSUARI(
    USUA_ID NUMBER(15),
    USUA_NOMBR VARCHAR2(50),
    USUA_APEPA VARCHAR(20),
    USUA_APEMA VARCHAR(20),
    USUA_NICKN VARCHAR2(10),
    USUA_PASSW VARCHAR2(100),
    USUA_EMAIL VARCHAR2(100),
    USUA_TIPO CHAR(2),
    USUA_EVENT VARCHAR2(1000),
    USUA_MUSIC VARCHAR2(1000),
    USUA_GENER VARCHAR2(100),
    USUA_DESCR VARCHAR2(1000), 
    PRIMARY KEY (USUA_ID)
);

CREATE TABLE USR_SREM.SREMEVENTO(
    EVEN_ID NUMBER(15),
    EVEN_NOMBR VARCHAR2(100),
    EVEN_UBICA VARCHAR2(100),
    EVEN_UBIDE VARCHAR2(200),
    EVEN_UBIRE VARCHAR2(200),
    EVEN_DISTR VARCHAR2(30),
    EVEN_REGIO VARCHAR2(30),
    EVEN_FYHIN TIMESTAMP,
    EVEN_FYHIA TIMESTAMP,
    EVEN_FYHFI TIMESTAMP,
    EVEN_DESCR CLOB,
    EVEN_PRECIO NUMBER(4),
    EVEN_ORGAN VARCHAR2(50),
    EVEN_ASIST NUMBER(5),
    EVEN_INTER NUMBER(5),
    EVEN_COMPA NUMBER(5),
    EVEN_VALOR NUMBER(3),
    EVEN_IMAGE VARCHAR2(1300),
    EVEN_LINKE VARCHAR2(1300),
    PRIMARY KEY (EVEN_ID)
);

CREATE TABLE USR_SREM.SREMPARGEN(
    PAGE_ID NUMBER(15),
    PAGE_CODIG VARCHAR2(50),
    PAGE_VALOR VARCHAR2(500),
    PAGE_DESCR VARCHAR2(200),
    PRIMARY KEY (PAGE_ID)
);

CREATE TABLE USR_SREM.SREMUSUAIN(
    USIN_ID NUMBER(15),
    USUA_ID NUMBER(15),
    EVEN_ID NUMBER(15),
    USUA_NICKN VARCHAR2(10),
    EVEN_NOMBR VARCHAR2(100),
    USIN_INTER NUMBER(3),
    USIN_VISIT NUMBER(3),
    USIN_VALOR NUMBER(3),
    PRIMARY KEY (USIN_ID)
);

--CREACION DE SECUENCIAS
--CREATE SEQUENCE  "USR_SREM"."SREMUSFACE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "USR_SREM"."SREMUSUARI_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "USR_SREM"."SREMEVENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "USR_SREM"."SREMPARGEN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "USR_SREM"."SREMUSUAIN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 500 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;


--INSERTAR DATA DE PRUEBA
INSERT INTO SREMUSUARI(USUA_ID,USUA_NOMBR,USUA_APEPA,USUA_APEMA,USUA_NICKN,USUA_PASSW,USUA_EMAIL,USUA_TIPO,USUA_EVENT,USUA_MUSIC,USUA_GENER,USUA_DESCR) values (SREMUSUARI_SEQ.NEXTVAL,'Jhonatan','Iba�ez','Taccsi','US001','US001','jhonatan.pp2207@gmail.com','AD','KEANE , BRYAN ADAMS','KEANE , BRYAN ADAMS','Rock , Instrumental','Persona amante de los conciertos y de la m�sica de Keane');
INSERT INTO SREMUSUARI(USUA_ID,USUA_NOMBR,USUA_APEPA,USUA_APEMA,USUA_NICKN,USUA_PASSW,USUA_EMAIL,USUA_TIPO,USUA_EVENT,USUA_MUSIC,USUA_GENER,USUA_DESCR) values (SREMUSUARI_SEQ.NEXTVAL,'Jose','Iba�ez','Taccsi','US002','US002','jose@gmail.com','US','FIESTA HALLOWEEN CON MIRANDA , BRYAN ADAMS','MIRANDA , BRYAN ADAMS','Rock , POP','');
INSERT INTO SREMUSUARI(USUA_ID,USUA_NOMBR,USUA_APEPA,USUA_APEMA,USUA_NICKN,USUA_PASSW,USUA_EMAIL,USUA_TIPO,USUA_EVENT,USUA_MUSIC,USUA_GENER,USUA_DESCR) values (SREMUSUARI_SEQ.NEXTVAL,'Maria','Iba�ez','Taccsi','US003','US003','maria@gmail.com','US','NOCHE DE GALA , CUMBIA VIP','GRUPO 5, ARMONIA 10','Cumbia , Salsa , Merengue','Vamos a bailar cumbiones!!');

INSERT INTO SREMEVENTO(EVEN_ID,EVEN_NOMBR,EVEN_UBICA,EVEN_UBIDE,EVEN_UBIRE,EVEN_DISTR,EVEN_REGIO,EVEN_FYHIN,EVEN_FYHIA,EVEN_FYHFI,EVEN_DESCR,EVEN_PRECIO,EVEN_ORGAN,EVEN_ASIST,EVEN_INTER,EVEN_COMPA,EVEN_VALOR,EVEN_IMAGE,EVEN_LINKE) VALUES (SREMEVENTO_SEQ.NEXTVAL);

INSERT INTO SREMUSUAIN(USIN_ID,USUA_ID,EVEN_ID,USUA_NICKN,EVEN_NOMBR,USIN_INTER,USIN_VISIT,USIN_VALOR) values (SREMUSUAIN_SEQ.NEXTVAL);



--Consultas de seleccion
SELECT EVEN_NOMBR, EVEN_UBICA, EVEN_UBIDE, EVEN_UBIRE, EVEN_DISTR, EVEN_REGIO, EVEN_FYHIN, EVEN_FYHIA, EVEN_FYHFI, EVEN_DESCR, EVEN_PRECIO, EVEN_ORGAN, EVEN_ASIST, EVEN_INTER, EVEN_COMPA, EVEN_VALOR, EVEN_IMAGE, EVEN_LINKE from SREMEVENTO;

SELECT USUA_NICKN, USUA_EVENT, USUA_MUSIC, USUA_GENER, USUA_DESCR FROM SREMUSUARI ORDER BY USUA_ID;

--=====================================================
--drop sequence "USR_SREM"."SREMUSFACE_SEQ";
drop table SREMEVENTO;
--delete from SREMUSUARI where USFA_ID=508;
delete from SREMEVENTO;
SELECT USUA_NICKN,USUA_EVENT,USUA_MUSIC,USUA_GENER,USUA_DESCR FROM SREMUSUARI; WHERE USFA_ID = 501;
select * from SREMUSUARI;
select * FROM SREMEVENTO;
select * FROM SREMPARGEN;
select * FROM SREMUSUAIN;

delete from SREMUSUARI where USUA_ID IN (4,5,6);

--